const mongoose = require("mongoose");
const Flight = require("./models/Flight");
const dns = require("dns");
dns.setServers(["8.8.8.8", "1.1.1.1"]);
const flights = [
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "دبي",
    fromCode: "CAI",
    toCode: "DXB",
    departDate: "2026-03-10",
    departTime: "08:00",
    arrivalTime: "12:30",
    duration: "4س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 3200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Saudia",
    fromCity: "جدة",
    toCity: "القاهرة",
    fromCode: "JED",
    toCode: "CAI",
    departDate: "2026-03-11",
    departTime: "10:00",
    arrivalTime: "11:30",
    duration: "2س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 850,
    currency: "ريال",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Emirates",
    fromCity: "دبي",
    toCity: "لندن",
    fromCode: "DXB",
    toCode: "LHR",
    departDate: "2026-03-12",
    departTime: "03:15",
    arrivalTime: "07:20",
    duration: "7س 05د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 2100,
    currency: "درهم",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Qatar Airways",
    fromCity: "الدوحة",
    toCity: "باريس",
    fromCode: "DOH",
    toCode: "CDG",
    departDate: "2026-03-13",
    departTime: "01:30",
    arrivalTime: "06:45",
    duration: "7س 15د",
    stops: "مباشر",
    flightClass: "أعمال",
    price: 12500,
    currency: "ريال",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "FlyDubai",
    fromCity: "الإسكندرية",
    toCity: "دبي",
    fromCode: "HBE",
    toCode: "DXB",
    departDate: "2026-03-14",
    departTime: "22:00",
    arrivalTime: "03:45",
    duration: "3س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 4500,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Turkish Airlines",
    fromCity: "إسطنبول",
    toCity: "نيويورك",
    fromCode: "IST",
    toCode: "JFK",
    departDate: "2026-03-15",
    departTime: "14:00",
    arrivalTime: "18:30",
    duration: "10س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 950,
    currency: "دولار",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Etihad Airways",
    fromCity: "أبوظبي",
    toCity: "الرياض",
    fromCode: "AUH",
    toCode: "RUH",
    departDate: "2026-03-16",
    departTime: "16:45",
    arrivalTime: "17:50",
    duration: "2س 05د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 700,
    currency: "درهم",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Air Arabia",
    fromCity: "الشارقة",
    toCity: "عمان",
    fromCode: "SHJ",
    toCode: "AMM",
    departDate: "2026-03-17",
    departTime: "09:10",
    arrivalTime: "11:20",
    duration: "3س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 650,
    currency: "درهم",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Lufthansa",
    fromCity: "فرانكفورت",
    toCity: "القاهرة",
    fromCode: "FRA",
    toCode: "CAI",
    departDate: "2026-03-18",
    departTime: "13:30",
    arrivalTime: "18:15",
    duration: "3س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 420,
    currency: "يورو",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "شرم الشيخ",
    fromCode: "CAI",
    toCode: "SSH",
    departDate: "2026-03-19",
    departTime: "07:00",
    arrivalTime: "08:00",
    duration: "1س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 1200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Royal Jordanian",
    fromCity: "عمان",
    toCity: "بيروت",
    fromCode: "AMM",
    toCode: "BEY",
    departDate: "2026-03-20",
    departTime: "11:00",
    arrivalTime: "12:05",
    duration: "1س 05د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 180,
    currency: "دينار",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Kuwait Airways",
    fromCity: "الكويت",
    toCity: "القاهرة",
    fromCode: "KWI",
    toCode: "CAI",
    departDate: "2026-03-21",
    departTime: "15:20",
    arrivalTime: "17:40",
    duration: "3س 20د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 95,
    currency: "دينار",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Flynas",
    fromCity: "الرياض",
    toCity: "أبها",
    fromCode: "RUH",
    toCode: "AHB",
    departDate: "2026-03-22",
    departTime: "20:00",
    arrivalTime: "21:35",
    duration: "1س 35د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 280,
    currency: "ريال",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Oman Air",
    fromCity: "مسقط",
    toCity: "بانكوك",
    fromCode: "MCT",
    toCode: "BKK",
    departDate: "2026-03-23",
    departTime: "09:00",
    arrivalTime: "18:20",
    duration: "6س 20د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 190,
    currency: "ريال عماني",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Air Cairo",
    fromCity: "سوهاج",
    toCity: "الكويت",
    fromCode: "HMB",
    toCode: "KWI",
    departDate: "2026-03-24",
    departTime: "04:00",
    arrivalTime: "06:45",
    duration: "2س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 2800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Gulf Air",
    fromCity: "البحرين",
    toCity: "القاهرة",
    fromCode: "BAH",
    toCode: "CAI",
    departDate: "2026-03-25",
    departTime: "10:30",
    arrivalTime: "13:00",
    duration: "3س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 110,
    currency: "دينار",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Middle East Airlines",
    fromCity: "بيروت",
    toCity: "باريس",
    fromCode: "BEY",
    toCode: "CDG",
    departDate: "2026-03-26",
    departTime: "08:15",
    arrivalTime: "12:00",
    duration: "4س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 450,
    currency: "دولار",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Jazeera Airways",
    fromCity: "الكويت",
    toCity: "مشهد",
    fromCode: "KWI",
    toCode: "MHD",
    departDate: "2026-03-27",
    departTime: "12:10",
    arrivalTime: "14:40",
    duration: "2س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 40,
    currency: "دينار",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "روما",
    fromCode: "CAI",
    toCode: "FCO",
    departDate: "2026-03-28",
    departTime: "09:40",
    arrivalTime: "13:10",
    duration: "3س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 6800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "British Airways",
    fromCity: "لندن",
    toCity: "نيويورك",
    fromCode: "LHR",
    toCode: "JFK",
    departDate: "2026-03-29",
    departTime: "11:15",
    arrivalTime: "14:30",
    duration: "8س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 550,
    currency: "جنيه استرليني",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Nile Air",
    fromCity: "القاهرة",
    toCity: "تبوك",
    fromCode: "CAI",
    toCode: "TUU",
    departDate: "2026-03-30",
    departTime: "17:00",
    arrivalTime: "19:15",
    duration: "2س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 2400,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Singapore Airlines",
    fromCity: "سنغافورة",
    toCity: "طوكيو",
    fromCode: "SIN",
    toCode: "HND",
    departDate: "2026-03-31",
    departTime: "23:55",
    arrivalTime: "07:30",
    duration: "6س 35د",
    stops: "مباشر",
    flightClass: "أولى",
    price: 4500,
    currency: "دولار سنغافوري",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Saudia",
    fromCity: "الرياض",
    toCity: "المدينة",
    fromCode: "RUH",
    toCode: "MED",
    departDate: "2026-03-10",
    departTime: "06:30",
    arrivalTime: "08:00",
    duration: "1س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 310,
    currency: "ريال",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Air France",
    fromCity: "باريس",
    toCity: "أمستردام",
    fromCode: "CDG",
    toCode: "AMS",
    departDate: "2026-03-11",
    departTime: "14:20",
    arrivalTime: "15:35",
    duration: "1س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 120,
    currency: "يورو",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Turkish Airlines",
    fromCity: "القاهرة",
    toCity: "إسطنبول",
    fromCode: "CAI",
    toCode: "IST",
    departDate: "2026-03-12",
    departTime: "21:15",
    arrivalTime: "00:40",
    duration: "2س 25د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 5200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Ryanair",
    fromCity: "مدريد",
    toCity: "روما",
    fromCode: "MAD",
    toCode: "CIA",
    departDate: "2026-03-13",
    departTime: "06:00",
    arrivalTime: "08:30",
    duration: "2س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 45,
    currency: "يورو",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Qantas",
    fromCity: "سيدني",
    toCity: "ملبورن",
    fromCode: "SYD",
    toCode: "MEL",
    departDate: "2026-03-14",
    departTime: "12:00",
    arrivalTime: "13:35",
    duration: "1س 35د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 180,
    currency: "دولار أسترالي",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "EgyptAir",
    fromCity: "أسوان",
    toCity: "القاهرة",
    fromCode: "ASW",
    toCode: "CAI",
    departDate: "2026-03-15",
    departTime: "23:00",
    arrivalTime: "00:25",
    duration: "1س 25د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 1100,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Qatar Airways",
    fromCity: "الدوحة",
    toCity: "مالي",
    fromCode: "DOH",
    toCode: "MLE",
    departDate: "2026-03-16",
    departTime: "02:10",
    arrivalTime: "09:00",
    duration: "4س 50د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 3400,
    currency: "ريال",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Emirates",
    fromCity: "دبي",
    toCity: "موسكو",
    fromCode: "DXB",
    toCode: "DME",
    departDate: "2026-03-17",
    departTime: "16:00",
    arrivalTime: "21:10",
    duration: "5س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 2800,
    currency: "درهم",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Nesma Airlines",
    fromCity: "القاهرة",
    toCity: "جدة",
    fromCode: "CAI",
    toCode: "JED",
    departDate: "2026-03-18",
    departTime: "01:00",
    arrivalTime: "04:15",
    duration: "2س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 2900,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Flyadeal",
    fromCity: "الدمام",
    toCity: "الرياض",
    fromCode: "DMM",
    toCode: "RUH",
    departDate: "2026-03-19",
    departTime: "18:30",
    arrivalTime: "19:40",
    duration: "1س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 150,
    currency: "ريال",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Lufthansa",
    fromCity: "ميونخ",
    toCity: "برلين",
    fromCode: "MUC",
    toCode: "BER",
    departDate: "2026-03-20",
    departTime: "09:00",
    arrivalTime: "10:10",
    duration: "1س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 140,
    currency: "يورو",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "KLM",
    fromCity: "أمستردام",
    toCity: "نيويورك",
    fromCode: "AMS",
    toCode: "JFK",
    departDate: "2026-03-21",
    departTime: "13:25",
    arrivalTime: "16:00",
    duration: "8س 35د",
    stops: "مباشر",
    flightClass: "أعمال",
    price: 2800,
    currency: "يورو",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Air India",
    fromCity: "دلهي",
    toCity: "مومباي",
    fromCode: "DEL",
    toCode: "BOM",
    departDate: "2026-03-22",
    departTime: "07:00",
    arrivalTime: "09:15",
    duration: "2س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 4500,
    currency: "روبية",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Cathay Pacific",
    fromCity: "هونج كونج",
    toCity: "تايبيه",
    fromCode: "HKG",
    toCode: "TPE",
    departDate: "2026-03-23",
    departTime: "10:50",
    arrivalTime: "12:45",
    duration: "1س 55د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 1500,
    currency: "دولار هونج كونج",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "EgyptAir",
    fromCity: "الأقصر",
    toCity: "القاهرة",
    fromCode: "LXR",
    toCode: "CAI",
    departDate: "2026-03-24",
    departTime: "06:00",
    arrivalTime: "07:10",
    duration: "1س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 1050,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Iberia",
    fromCity: "مدريد",
    toCity: "برشلونة",
    fromCode: "MAD",
    toCode: "BCN",
    departDate: "2026-03-25",
    departTime: "20:30",
    arrivalTime: "21:45",
    duration: "1س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 60,
    currency: "يورو",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Saudia",
    fromCity: "القاهرة",
    toCity: "الرياض",
    fromCode: "CAI",
    toCode: "RUH",
    departDate: "2026-03-26",
    departTime: "14:00",
    arrivalTime: "17:30",
    duration: "2س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 3800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Alitalia",
    fromCity: "روما",
    toCity: "ميلانو",
    fromCode: "FCO",
    toCode: "LIN",
    departDate: "2026-03-27",
    departTime: "08:00",
    arrivalTime: "09:10",
    duration: "1س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 85,
    currency: "يورو",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "United Airlines",
    fromCity: "شيكاغو",
    toCity: "لوس أنجلوس",
    fromCode: "ORD",
    toCode: "LAX",
    departDate: "2026-03-28",
    departTime: "10:30",
    arrivalTime: "13:00",
    duration: "4س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 220,
    currency: "دولار",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Royal Air Maroc",
    fromCity: "الدار البيضاء",
    toCity: "تونس",
    fromCode: "CMN",
    toCode: "TUN",
    departDate: "2026-03-29",
    departTime: "13:45",
    arrivalTime: "16:30",
    duration: "2س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 2100,
    currency: "درهم مغربي",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "الكويت",
    fromCode: "CAI",
    toCode: "KWI",
    departDate: "2026-03-30",
    departTime: "23:30",
    arrivalTime: "02:15",
    duration: "2س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 4100,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Delta Air Lines",
    fromCity: "أتلانتا",
    toCity: "ميامي",
    fromCode: "ATL",
    toCode: "MIA",
    departDate: "2026-03-31",
    departTime: "15:20",
    arrivalTime: "17:15",
    duration: "1س 55د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 140,
    currency: "دولار",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "SalamAir",
    fromCity: "مسقط",
    toCity: "صلالة",
    fromCode: "MCT",
    toCode: "SLL",
    departDate: "2026-03-10",
    departTime: "19:00",
    arrivalTime: "20:40",
    duration: "1س 40د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 35,
    currency: "ريال عماني",
    hasLuggage: false,
    tripType: "oneway",
  },
  {
    airline: "Middle East Airlines",
    fromCity: "القاهرة",
    toCity: "بيروت",
    fromCode: "CAI",
    toCode: "BEY",
    departDate: "2026-03-11",
    departTime: "16:30",
    arrivalTime: "17:50",
    duration: "1س 20د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 4200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Air Canada",
    fromCity: "تورونتو",
    toCity: "فانكوفر",
    fromCode: "YYZ",
    toCode: "YVR",
    departDate: "2026-03-12",
    departTime: "08:00",
    arrivalTime: "10:15",
    duration: "5س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 350,
    currency: "دولار كندي",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "أثينا",
    fromCode: "CAI",
    toCode: "ATH",
    departDate: "2026-03-13",
    departTime: "10:15",
    arrivalTime: "12:15",
    duration: "2س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 5800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "Qatar Airways",
    fromCity: "لندن",
    toCity: "الدوحة",
    fromCode: "LHR",
    toCode: "DOH",
    departDate: "2026-03-14",
    departTime: "20:30",
    arrivalTime: "06:15",
    duration: "6س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 620,
    currency: "جنيه استرليني",
    hasLuggage: true,
    tripType: "oneway",
  },
  {
    airline: "flynas",
    fromCity: "جدة",
    toCity: "دبي",
    fromCode: "JED",
    toCode: "DXB",
    departDate: "2026-03-15",
    departTime: "11:00",
    arrivalTime: "14:45",
    duration: "2س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 450,
    currency: "ريال",
    hasLuggage: false,
    tripType: "oneway",
  },
    {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "دبي",
    fromCode: "CAI",
    toCode: "DXB",
    departDate: new Date("2026-03-10"),
    returnDate: new Date("2026-03-17"),
    departTime: "08:00",
    arrivalTime: "12:30",
    returnTime: "15:00",
    duration: "4س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 8500,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Saudi Arabian Airlines",
    fromCity: "القاهرة",
    toCity: "جدة",
    fromCode: "CAI",
    toCode: "JED",
    departDate: new Date("2026-03-12"),
    returnDate: new Date("2026-03-19"),
    departTime: "10:00",
    arrivalTime: "13:00",
    returnTime: "22:00",
    duration: "2س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 9200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Emirates",
    fromCity: "دبي",
    toCity: "لندن",
    fromCode: "DXB",
    toCode: "LHR",
    departDate: new Date("2026-03-15"),
    returnDate: new Date("2026-03-25"),
    departTime: "09:00",
    arrivalTime: "13:30",
    returnTime: "20:00",
    duration: "7س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 24500,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Turkish Airlines",
    fromCity: "القاهرة",
    toCity: "إسطنبول",
    fromCode: "CAI",
    toCode: "IST",
    departDate: new Date("2026-03-20"),
    returnDate: new Date("2026-03-27"),
    departTime: "03:30",
    arrivalTime: "06:45",
    returnTime: "18:00",
    duration: "2س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 11800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Qatar Airways",
    fromCity: "الدوحة",
    toCity: "باريس",
    fromCode: "DOH",
    toCode: "CDG",
    departDate: new Date("2026-04-01"),
    returnDate: new Date("2026-04-10"),
    departTime: "08:00",
    arrivalTime: "14:00",
    returnTime: "21:00",
    duration: "7س 00د",
    stops: "مباشر",
    flightClass: "درجة رجال الأعمال",
    price: 55000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Lufthansa",
    fromCity: "القاهرة",
    toCity: "فرانكفورت",
    fromCode: "CAI",
    toCode: "FRA",
    departDate: new Date("2026-04-05"),
    returnDate: new Date("2026-04-15"),
    departTime: "05:50",
    arrivalTime: "10:30",
    returnTime: "14:00",
    duration: "4س 40د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 19500,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Air Cairo",
    fromCity: "الغردقة",
    toCity: "براغ",
    fromCode: "HRG",
    toCode: "PRG",
    departDate: new Date("2026-04-07"),
    returnDate: new Date("2026-04-14"),
    departTime: "14:00",
    arrivalTime: "18:30",
    returnTime: "20:00",
    duration: "4س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 12400,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Etihad Airways",
    fromCity: "أبوظبي",
    toCity: "روما",
    fromCode: "AUH",
    toCode: "FCO",
    departDate: new Date("2026-04-10"),
    returnDate: new Date("2026-04-20"),
    departTime: "02:15",
    arrivalTime: "06:45",
    returnTime: "11:00",
    duration: "6س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 17800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Nile Air",
    fromCity: "القاهرة",
    toCity: "الكويت",
    fromCode: "CAI",
    toCode: "KWI",
    departDate: new Date("2026-04-12"),
    returnDate: new Date("2026-04-19"),
    departTime: "11:00",
    arrivalTime: "14:30",
    returnTime: "16:00",
    duration: "2س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 7600,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Wizz Air",
    fromCity: "القاهرة",
    toCity: "روما",
    fromCode: "CAI",
    toCode: "FCO",
    departDate: new Date("2026-04-15"),
    returnDate: new Date("2026-04-22"),
    departTime: "20:00",
    arrivalTime: "23:45",
    returnTime: "01:00",
    duration: "3س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 5200,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "roundtrip",
  },
  {
    airline: "Middle East Airlines",
    fromCity: "بيروت",
    toCity: "مدريد",
    fromCode: "BEY",
    toCode: "MAD",
    departDate: new Date("2026-04-18"),
    returnDate: new Date("2026-04-25"),
    departTime: "09:00",
    arrivalTime: "13:30",
    returnTime: "16:00",
    duration: "5س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 14200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Flydubai",
    fromCity: "الإسكندرية",
    toCity: "دبي",
    fromCode: "HBE",
    toCode: "DXB",
    departDate: new Date("2026-04-20"),
    returnDate: new Date("2026-04-27"),
    departTime: "01:00",
    arrivalTime: "06:30",
    returnTime: "22:00",
    duration: "3س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 8900,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Royal Jordanian",
    fromCity: "عمان",
    toCity: "أثينا",
    fromCode: "AMM",
    toCode: "ATH",
    departDate: new Date("2026-05-01"),
    returnDate: new Date("2026-05-08"),
    departTime: "10:30",
    arrivalTime: "12:45",
    returnTime: "15:00",
    duration: "2س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 10500,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Air France",
    fromCity: "باريس",
    toCity: "نيويورك",
    fromCode: "CDG",
    toCode: "JFK",
    departDate: new Date("2026-05-05"),
    returnDate: new Date("2026-05-15"),
    departTime: "13:30",
    arrivalTime: "15:45",
    returnTime: "21:00",
    duration: "8س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 32000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "كانو",
    fromCode: "CAI",
    toCode: "KAN",
    departDate: new Date("2026-05-10"),
    returnDate: new Date("2026-05-17"),
    departTime: "02:00",
    arrivalTime: "06:30",
    returnTime: "09:00",
    duration: "5س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 15600,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "British Airways",
    fromCity: "لندن",
    toCity: "طوكيو",
    fromCode: "LHR",
    toCode: "HND",
    departDate: new Date("2026-05-12"),
    returnDate: new Date("2026-05-22"),
    departTime: "14:00",
    arrivalTime: "10:00",
    returnTime: "12:00",
    duration: "13س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 68000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Gulf Air",
    fromCity: "البحرين",
    toCity: "بانكوك",
    fromCode: "BAH",
    toCode: "BKK",
    departDate: new Date("2026-05-15"),
    returnDate: new Date("2026-05-25"),
    departTime: "22:00",
    arrivalTime: "10:00",
    returnTime: "14:00",
    duration: "8س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 29000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Austrian Airlines",
    fromCity: "فيينا",
    toCity: "القاهرة",
    fromCode: "VIE",
    toCode: "CAI",
    departDate: new Date("2026-05-20"),
    returnDate: new Date("2026-05-27"),
    departTime: "10:00",
    arrivalTime: "13:30",
    returnTime: "16:00",
    duration: "3س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 16800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "KLM",
    fromCity: "أمستردام",
    toCity: "كيب تاون",
    fromCode: "AMS",
    toCode: "CPT",
    departDate: new Date("2026-06-01"),
    returnDate: new Date("2026-06-15"),
    departTime: "10:15",
    arrivalTime: "22:30",
    returnTime: "00:15",
    duration: "11س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 42000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Jazeera Airways",
    fromCity: "الكويت",
    toCity: "إسطنبول",
    fromCode: "KWI",
    toCode: "IST",
    departDate: new Date("2026-06-05"),
    returnDate: new Date("2026-06-12"),
    departTime: "12:00",
    arrivalTime: "15:45",
    returnTime: "18:00",
    duration: "3س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 9400,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "ميلانو",
    fromCode: "CAI",
    toCode: "MXP",
    departDate: new Date("2026-06-10"),
    returnDate: new Date("2026-06-20"),
    departTime: "10:00",
    arrivalTime: "13:50",
    returnTime: "16:00",
    duration: "3س 50د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 14500,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Singapore Airlines",
    fromCity: "سنغافورة",
    toCity: "سيدني",
    fromCode: "SIN",
    toCode: "SYD",
    departDate: new Date("2026-06-15"),
    returnDate: new Date("2026-06-25"),
    departTime: "00:10",
    arrivalTime: "10:30",
    returnTime: "21:00",
    duration: "8س 20د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 35000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Iberia",
    fromCity: "مدريد",
    toCity: "مكسيكو سيتي",
    fromCode: "MAD",
    toCode: "MEX",
    departDate: new Date("2026-06-20"),
    returnDate: new Date("2026-07-05"),
    departTime: "11:30",
    arrivalTime: "17:15",
    returnTime: "20:00",
    duration: "11س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 48000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Oman Air",
    fromCity: "مسقط",
    toCity: "لندن",
    fromCode: "MCT",
    toCode: "LHR",
    departDate: new Date("2026-07-01"),
    returnDate: new Date("2026-07-15"),
    departTime: "14:00",
    arrivalTime: "19:10",
    returnTime: "21:30",
    duration: "8س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 31000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Air Arabia",
    fromCity: "الشارقة",
    toCity: "القاهرة",
    fromCode: "SHJ",
    toCode: "CAI",
    departDate: new Date("2026-07-05"),
    returnDate: new Date("2026-07-12"),
    departTime: "09:00",
    arrivalTime: "11:30",
    returnTime: "14:00",
    duration: "3س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 7800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "شرم الشيخ",
    toCity: "نابولي",
    fromCode: "SSH",
    toCode: "NAP",
    departDate: new Date("2026-07-10"),
    returnDate: new Date("2026-07-17"),
    departTime: "15:00",
    arrivalTime: "18:45",
    returnTime: "20:00",
    duration: "3س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 13200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Swiss Air",
    fromCity: "زيورخ",
    toCity: "طوكيو",
    fromCode: "ZRH",
    toCode: "NRT",
    departDate: new Date("2026-07-15"),
    returnDate: new Date("2026-07-30"),
    departTime: "13:00",
    arrivalTime: "08:00",
    returnTime: "11:00",
    duration: "12س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 65000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Royal Air Maroc",
    fromCity: "الدار البيضاء",
    toCity: "نيويورك",
    fromCode: "CMN",
    toCode: "JFK",
    departDate: new Date("2026-08-01"),
    returnDate: new Date("2026-08-15"),
    departTime: "16:00",
    arrivalTime: "19:00",
    returnTime: "22:00",
    duration: "8س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 38000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Aegean Airlines",
    fromCity: "أثينا",
    toCity: "مدريد",
    fromCode: "ATH",
    toCode: "MAD",
    departDate: new Date("2026-08-05"),
    returnDate: new Date("2026-08-12"),
    departTime: "08:30",
    arrivalTime: "11:15",
    returnTime: "14:00",
    duration: "3س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 9800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "برشلونة",
    fromCode: "CAI",
    toCode: "BCN",
    departDate: new Date("2026-08-10"),
    returnDate: new Date("2026-08-20"),
    departTime: "09:30",
    arrivalTime: "13:45",
    returnTime: "16:00",
    duration: "4س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 15900,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Flynas",
    fromCity: "الرياض",
    toCity: "القاهرة",
    fromCode: "RUH",
    toCode: "CAI",
    departDate: new Date("2026-08-15"),
    returnDate: new Date("2026-08-22"),
    departTime: "22:00",
    arrivalTime: "00:30",
    returnTime: "03:00",
    duration: "2س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 6400,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "roundtrip",
  },
  {
    airline: "IndiGo",
    fromCity: "دبي",
    toCity: "مومباي",
    fromCode: "DXB",
    toCode: "BOM",
    departDate: new Date("2026-08-20"),
    returnDate: new Date("2026-08-27"),
    departTime: "21:00",
    arrivalTime: "01:30",
    returnTime: "04:00",
    duration: "3س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 9200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Flyadeal",
    fromCity: "جدة",
    toCity: "القاهرة",
    fromCode: "JED",
    toCode: "CAI",
    departDate: new Date("2026-09-01"),
    returnDate: new Date("2026-09-08"),
    departTime: "15:00",
    arrivalTime: "17:15",
    returnTime: "19:00",
    duration: "2س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 5800,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "roundtrip",
  },
  {
    airline: "Ryanair",
    fromCity: "روما",
    toCity: "باريس",
    fromCode: "FCO",
    toCode: "BVA",
    departDate: new Date("2026-09-05"),
    returnDate: new Date("2026-09-12"),
    departTime: "07:00",
    arrivalTime: "09:10",
    returnTime: "11:00",
    duration: "2س 10د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 3200,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "تونس",
    fromCode: "CAI",
    toCode: "TUN",
    departDate: new Date("2026-09-10"),
    returnDate: new Date("2026-09-17"),
    departTime: "08:15",
    arrivalTime: "10:30",
    returnTime: "12:00",
    duration: "3س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 11200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Tunisair",
    fromCity: "تونس",
    toCity: "باريس",
    fromCode: "TUN",
    toCode: "ORY",
    departDate: new Date("2026-09-15"),
    returnDate: new Date("2026-09-22"),
    departTime: "09:00",
    arrivalTime: "11:45",
    returnTime: "14:00",
    duration: "2س 45د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 10400,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Cathay Pacific",
    fromCity: "هونج كونج",
    toCity: "سان فرانسيسكو",
    fromCode: "HKG",
    toCode: "SFO",
    departDate: new Date("2026-10-01"),
    returnDate: new Date("2026-10-15"),
    departTime: "23:00",
    arrivalTime: "20:00",
    returnTime: "22:00",
    duration: "12س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 45000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Badr Airlines",
    fromCity: "القاهرة",
    toCity: "بورتسودان",
    fromCode: "CAI",
    toCode: "PZU",
    departDate: new Date("2026-10-05"),
    returnDate: new Date("2026-10-12"),
    departTime: "10:00",
    arrivalTime: "13:00",
    returnTime: "15:00",
    duration: "3س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 12500,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Nesma Airlines",
    fromCity: "القاهرة",
    toCity: "تبوك",
    fromCode: "CAI",
    toCode: "TUU",
    departDate: new Date("2026-10-10"),
    returnDate: new Date("2026-10-17"),
    departTime: "11:00",
    arrivalTime: "13:30",
    returnTime: "15:00",
    duration: "1س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 6800,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "عمان",
    fromCode: "CAI",
    toCode: "AMM",
    departDate: new Date("2026-10-15"),
    returnDate: new Date("2026-10-22"),
    departTime: "16:00",
    arrivalTime: "17:20",
    returnTime: "19:00",
    duration: "1س 20د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 7400,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Kuwait Airways",
    fromCity: "الكويت",
    toCity: "لندن",
    fromCode: "KWI",
    toCode: "LHR",
    departDate: new Date("2026-11-01"),
    returnDate: new Date("2026-11-10"),
    departTime: "09:30",
    arrivalTime: "14:00",
    returnTime: "18:00",
    duration: "6س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 26000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Salam Air",
    fromCity: "مسقط",
    toCity: "صلالة",
    fromCode: "MCT",
    toCode: "SLL",
    departDate: new Date("2026-11-05"),
    returnDate: new Date("2026-11-12"),
    departTime: "08:00",
    arrivalTime: "09:40",
    returnTime: "18:00",
    duration: "1س 40د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 4200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Air India",
    fromCity: "دلهي",
    toCity: "لندن",
    fromCode: "DEL",
    toCode: "LHR",
    departDate: new Date("2026-11-10"),
    returnDate: new Date("2026-11-20"),
    departTime: "02:30",
    arrivalTime: "07:30",
    returnTime: "11:00",
    duration: "9س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 29000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "جوانزو",
    fromCode: "CAI",
    toCode: "CAN",
    departDate: new Date("2026-11-15"),
    returnDate: new Date("2026-11-30"),
    departTime: "23:30",
    arrivalTime: "15:30",
    returnTime: "21:00",
    duration: "11س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 42000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Vueling",
    fromCity: "برشلونة",
    toCity: "لشبونة",
    fromCode: "BCN",
    toCode: "LIS",
    departDate: new Date("2026-11-20"),
    returnDate: new Date("2026-11-27"),
    departTime: "10:00",
    arrivalTime: "11:55",
    returnTime: "14:00",
    duration: "1س 55د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 3800,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "roundtrip",
  },
  {
    airline: "Air Canada",
    fromCity: "تورونتو",
    toCity: "فانكوفر",
    fromCode: "YYZ",
    toCode: "YVR",
    departDate: new Date("2026-12-01"),
    returnDate: new Date("2026-12-10"),
    departTime: "08:00",
    arrivalTime: "10:15",
    returnTime: "15:00",
    duration: "5س 15د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 18000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "EgyptAir",
    fromCity: "القاهرة",
    toCity: "أسوان",
    fromCode: "CAI",
    toCode: "ASW",
    departDate: new Date("2026-12-15"),
    returnDate: new Date("2026-12-22"),
    departTime: "06:00",
    arrivalTime: "07:30",
    returnTime: "20:00",
    duration: "1س 30د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 3200,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "Etihad Airways",
    fromCity: "أبوظبي",
    toCity: "طوكيو",
    fromCode: "AUH",
    toCode: "NRT",
    departDate: new Date("2026-12-20"),
    returnDate: new Date("2027-01-05"),
    departTime: "22:00",
    arrivalTime: "13:00",
    returnTime: "17:00",
    duration: "10س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 36000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  },
  {
    airline: "FlyOne",
    fromCity: "القاهرة",
    toCity: "يريفان",
    fromCode: "CAI",
    toCode: "EVN",
    departDate: new Date("2026-12-25"),
    returnDate: new Date("2027-01-02"),
    departTime: "14:00",
    arrivalTime: "18:00",
    returnTime: "20:00",
    duration: "3س 00د",
    stops: "مباشر",
    flightClass: "اقتصادي",
    price: 8400,
    currency: "جنيه",
    hasLuggage: false,
    tripType: "roundtrip",
  },
  {
    airline: "Emirates",
    fromCity: "دبي",
    toCity: "القاهرة",
    fromCode: "DXB",
    toCode: "CAI",
    departDate: new Date("2026-12-30"),
    returnDate: new Date("2027-01-07"),
    departTime: "15:00",
    arrivalTime: "17:30",
    returnTime: "21:00",
    duration: "4س 30د",
    stops: "مباشر",
    flightClass: "درجة رجال الأعمال",
    price: 38000,
    currency: "جنيه",
    hasLuggage: true,
    tripType: "roundtrip",
  }
];
require("dotenv").config();

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    await Flight.deleteMany();
    await Flight.insertMany(flights);
    console.log("Flights Seeded Successfully");
    process.exit();
  })
  .catch((err) => console.log(err));
